services:
  - type: web
    name: audiosnap-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p ffmpeg
      curl -L "https://drive.google.com/drive/folders/1kOEza0xLh46svzafW9OJHJ6lkRvn4d99?usp=sharing" -o ffmpeg/ffmpeg
      chmod +x ffmpeg/ffmpeg
    startCommand: gunicorn backend:app
